metersphere/metersphere

backend/src/main/java/io/metersphere/api/controller/ApiMonitorController.java, backend/src/main/java/io/metersphere/api/dto/ApiMonitorSearch.java, backend/src/main/java/io/metersphere/api/dto/ApiResponseCodeMonitor.java, backend/src/main/java/io/metersphere/api/dto/ApiResponseTimeMonitor.java, backend/src/main/java/io/metersphere/api/service/APIMonitorService.java, backend/src/main/java/io/metersphere/api/service/APIReportService.java, backend/src/main/java/io/metersphere/base/domain/ApiDataView.java, backend/src/main/java/io/metersphere/base/mapper/ApiDataViewMapper.java, backend/src/main/java/io/metersphere/base/mapper/ApiDataViewMapper.xml, backend/src/main/resources/db/migration/V47__api_data_view.sql, frontend/src/business/components/api/head/ApiHeaderMenus.vue, frontend/src/business/components/api/monitor/ApiMonitor.vue, frontend/src/business/components/api/monitor/ApiMonitorChart.vue, frontend/src/business/components/api/monitor/ApiMonitorSearch.vue, frontend/src/business/components/api/monitor/components/ApiErrorMonitorChart.vue, frontend/src/business/components/api/monitor/components/ApiResponseTimeMonitorChart.vue, frontend/src/business/components/api/monitor/components/CommonMonitorChart.vue, frontend/src/business/components/api/router.js, frontend/src/common/js/ajax.js, frontend/src/common/js/chart.js, frontend/src/common/js/format-utils.js, frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
在每次报告生成时取出每一条http接口信息并以图表形式显示 
在删除报告时同时删除接口信息
=> feat(接口监控):增加响应时间与状态监控功能

frontend/src/common/js/ajax.js
=> fix(登陆)：修复登陆密码错误时 提示重新登陆

frontend/src/business/components/settings/project/MsProject.vue
=> fix：解决 创建新项目编辑-描述输入框无法换行

frontend/src/business/components/common/cron/CrontabHour.vue
=> fix:解决 定时任务生成表达式 指定小时下拉框列表内容不正确

backend/src/main/java/io/metersphere/commons/utils/JsonPathUtils.java
bugfix 修复'[]'格式json解析错误问题
https://github.com/metersphere/metersphere/issues/1144
=> bugfix 修复'[]'格式json解析错误问题

frontend/src/business/components/api/automation/ApiAutomation.vue, frontend/src/business/components/api/automation/scenario/EditApiScenario.vue, frontend/src/business/components/api/definition/ApiDefinition.vue, frontend/src/business/components/api/definition/components/ApiConfig.vue, frontend/src/business/components/api/definition/components/complete/EditCompleteDubboApi.vue, frontend/src/business/components/api/definition/components/complete/EditCompleteHTTPApi.vue, frontend/src/business/components/api/definition/components/complete/EditCompleteSQLApi.vue, frontend/src/business/components/api/definition/components/complete/EditCompleteTCPApi.vue, frontend/src/common/js/utils.js
feat:实现 接口测试-接口定义界面，ctrl + s 保存快捷键
=> feat:实现 接口测试-接口定义界面，ctrl + s 保存快捷键

backend/src/main/java/io/metersphere/api/service/ApiAutomationService.java, backend/src/main/java/io/metersphere/api/service/ApiModuleService.java, backend/src/main/java/io/metersphere/api/service/ApiScenarioModuleService.java, backend/src/main/java/io/metersphere/base/mapper/ext/ExtApiDefinitionMapper.java, backend/src/main/java/io/metersphere/base/mapper/ext/ExtApiDefinitionMapper.xml, backend/src/main/java/io/metersphere/base/mapper/ext/ExtApiScenarioMapper.java, backend/src/main/java/io/metersphere/base/mapper/ext/ExtApiScenarioMapper.xml
feat: (接口定义、接口自动化) 删除模块时，模块下的所有接口或场景被放入回收站
=> feat: (接口定义、接口自动化) 删除模块时，模块下的所有接口或场景被放入回收站

backend/src/main/java/io/metersphere/api/service/ApiAutomationService.java, backend/src/main/java/io/metersphere/api/service/ApiModuleService.java, backend/src/main/java/io/metersphere/api/service/ApiScenarioModuleService.java, backend/src/main/java/io/metersphere/base/mapper/ext/ExtApiDefinitionMapper.java, backend/src/main/java/io/metersphere/base/mapper/ext/ExtApiDefinitionMapper.xml, backend/src/main/java/io/metersphere/base/mapper/ext/ExtApiScenarioMapper.java, backend/src/main/java/io/metersphere/base/mapper/ext/ExtApiScenarioMapper.xml, frontend/src/business/components/api/automation/scenario/ApiScenarioList.vue, frontend/src/business/components/api/definition/components/list/ApiCaseSimpleList.vue, frontend/src/business/components/api/definition/components/list/ApiList.vue, frontend/src/business/components/track/case/components/TestCaseList.vue
=> feat:在接口列表等窗口中，可点击ID进入编辑页面

frontend/src/business/components/api/definition/components/list/ApiList.vue
fix: (接口定义) 解决在回收站中，Case切换到Api时未显示回收站内容问题
=> fix: (接口定义) 解决在回收站中，Case切换到Api时未显示回收站内容问题

frontend/src/business/components/track/plan/view/comonents/api/RelevanceScenarioList.vue
=> fix: (测试计划) 解决关联场景用例时tag字段不显示

backend/src/main/java/io/metersphere/track/service/TestPlanService.java, frontend/src/business/components/track/plan/components/TestPlanList.vue
fix: (测试计划) 修复 测试计划-修改状态后时间显示有误
=> fix: (测试计划) 修复 测试计划-修改状态后时间显示有误

frontend/src/business/components/api/automation/scenario/variable/EditConstant.vue
=> fix: 解决 接口自动化-添加场景变量，焦点错误切换

frontend/src/business/components/api/definition/components/case/ApiCaseItem.vue
=> fix: (接口定义) 将接口另存为新用例后，方法名会被前端自动替换为协议

frontend/src/business/components/api/definition/components/case/ApiCaseList.vue
=> fix: 修复新建接口，另存为用例后，修改接口路径，用例没有同步

frontend/src/business/components/api/automation/scenario/common/ApiBaseComponent.vue
添加断言、等待控制器、前置脚本、后置脚本、提取参数  光标聚焦到对应的名称输入框，详细信息无需再次点击展开
=> style(接口定义): 添加断言、等待控制器、前置脚本、后置脚本、提取参数  光标聚焦到输入框，自动展开

backend/src/main/java/io/metersphere/track/service/TestPlanReportService.java
=> refactor: 删除不必要的注释代码（示例）

backend/src/main/java/io/metersphere/api/service/ApiAutomationService.java, backend/src/main/java/io/metersphere/api/service/ApiScenarioReportService.java, backend/src/main/java/io/metersphere/api/service/task/SerialScenarioExecTask.java
Reverts metersphere/metersphere#8589
=> Revert "fix(测试计划): 修复测试计划获取没有步骤结果场景时不会处理报告记录的问题"

backend/src/main/java/io/metersphere/api/dto/definition/SaveApiDefinitionRequest.java, backend/src/main/java/io/metersphere/api/service/ApiDefinitionService.java, backend/src/main/java/io/metersphere/commons/utils/FileUtils.java, frontend/src/business/components/api/definition/components/ApiConfig.vue
--bug=1011224 --user=赵勇 【接口测试】复制接口（请求体中含有文件）-执行复制的接口报错：找不到文件 https://www.tapd.cn/55049933/s/1118072
=> fix(接口测试): 修复接口复制附件丢失问题

backend/src/main/java/io/metersphere/commons/utils/FileUtils.java, backend/src/main/java/io/metersphere/track/issue/AbstractIssuePlatform.java, backend/src/main/java/io/metersphere/track/issue/IssuesPlatform.java, backend/src/main/java/io/metersphere/track/issue/domain/azure/AzureDevopsWorkItemsBatchResponse.java, backend/src/main/java/io/metersphere/track/request/testcase/IssuesUpdateRequest.java, backend/src/main/java/io/metersphere/track/service/IssuesService.java, backend/src/main/java/io/metersphere/track/service/TestCaseService.java, frontend/src/business/components/track/case/components/TestCaseIssueRelate.vue
fix:azure devops平台创建的bug未同步到metersphere(#ID1010762)
fix:github#11072，Azure Devops 提交缺陷 ，不支持上传图片(#ID1010759)
fix:tfs 缺陷和需求关联，缺陷能够挂在需求下(#ID1004746)
还有backend 的 x-pack 也需要合并，xpack分支：pr@master@fix_azure_devops_bug_sync
=> fix:azure devops平台缺陷同步问题处理

backend/src/main/java/io/metersphere/track/issue/AbstractIssuePlatform.java, backend/src/main/java/io/metersphere/track/issue/IssuesPlatform.java, backend/src/main/java/io/metersphere/track/service/TestCaseService.java
--story=ID1006739 --user=赵乾 需求与用例关联关系实时同步azure devops
=> fix(接口测试): 需求与用例关联关系实时同步azure devops

backend/src/main/java/io/metersphere/track/issue/ZentaoPlatform.java, backend/src/main/java/io/metersphere/track/issue/client/ZentaoClient.java
--bug=1011584 --user=zhaoqian
1、开源版，在ms关联禅道平台，创建缺陷，添加图片，提交
2、在禅道上修改一下缺陷，回到ms同步缺陷，同步后，图片不显示了
=> fix(接口测试): 缺陷管理-禅道缺陷往ms同步，图片不显示

SECURITY.md
=> docs: 更新安全说明联系邮箱

backend/src/main/java/io/metersphere/track/issue/JiraPlatform.java, backend/src/main/java/io/metersphere/track/issue/client/BaseClient.java, backend/src/main/java/io/metersphere/track/issue/client/JiraAbstractClient.java
--bug=1011584 --user=zhaoqian
修改了缺陷上传、更新、同步功能中关于附件的相关处理
=> fix(接口测试): 缺陷管理-jira缺陷往ms同步，图片不显示

backend/src/main/java/io/metersphere/track/issue/domain/azure/AzureDevopsWorkItemsBatchResponse.java
--bug=1012110 --user=zhaoqian
用户在tfs平台自定义缺陷模板，添加自定义字段，无法同步到ms的问题处理
还有xpack的pr合并后 需要更新xapck的引用
=> fix(接口测试): tfs平台缺陷模板添加自定义字段 同步问题处理

frontend/src/business/components/track/case/components/IssueRelateList.vue
=> refactor(测试跟踪): 关联缺陷界面增加搜索功能

backend/src/main/java/io/metersphere/track/issue/client/ZentaoClient.java
--user=zhaoqian
解决禅道pro版缺陷同步图片路径错误问题
=> fix(接口测试): 禅道pro版缺陷同步图片路径错误问题

README.md
add  release version badges for README.md.
add  release version badges for README.md.
=> docs: 增加徽章

backend/src/main/java/io/metersphere/commons/constants/ZentaoIssuePlatformStatus.java, backend/src/main/java/io/metersphere/track/controller/IssuesController.java, backend/src/main/java/io/metersphere/track/dto/PlatformStatusDTO.java, backend/src/main/java/io/metersphere/track/issue/AbstractIssuePlatform.java, backend/src/main/java/io/metersphere/track/issue/JiraPlatform.java, backend/src/main/java/io/metersphere/track/issue/TapdPlatform.java, backend/src/main/java/io/metersphere/track/issue/ZentaoPlatform.java, backend/src/main/java/io/metersphere/track/request/issues/PlatformIssueTypeRequest.java, backend/src/main/java/io/metersphere/track/request/testcase/IssuesUpdateRequest.java, backend/src/main/java/io/metersphere/track/service/IssuesService.java, backend/src/main/resources/i18n/messages_en_US.properties, backend/src/main/resources/i18n/messages_zh_CN.properties, backend/src/main/resources/i18n/messages_zh_TW.properties, frontend/src/business/components/track/issue/IssueEditDetail.vue, frontend/src/business/components/track/issue/IssueList.vue, frontend/src/common/js/table-constants.js, frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js, frontend/src/network/Issue.js
--bug=1012113
--user=zhaoqian
【缺陷列表】【平台状态】字段无法编辑，且ms字段与第三方平台字段重复
https://www.tapd.cn/55049933/bugtrace/bugs/view/1155049933001012113
=> fix(缺陷管理): 缺陷管理列表平台状态字段无法编辑问题处理

frontend/src/business/components/common/router/router.js, frontend/src/business/components/performance/v_node_diff.js, frontend/src/common/js/custom_field.js
Signed-off-by: Ryan Wang <i@ryanc.cc>
移除无用的 console log。
移除无用的 console log。
=> chore: cleanup unnecessary console log

frontend/src/business/components/api/automation/scenario/DebugRun.vue
格式化部分代码，以统一代码格式
格式化 [DebugRun.vueL96](https://github.com/metersphere/metersphere/blob/c1710d5d80cb80d8c4f72a9f19725b12e603c6a7/frontend/src/business/components/api/automation/scenario/DebugRun.vue#L96)
=> chore: format partial code

frontend/src/business/components/api/automation/scenario/EditApiScenario.vue
Typo issue.
- Change `plugnOrder` to `pluginOrder`.
- Format two lines.
=> typo(EditApiScenario): plugnOrder -> pluginOrder (#1)

frontend/src/business/components/api/automation/report/components/ScenarioResult.vue
getLable -> getLabel
getLable -> getLabel
=> typo(ScenarioResult): getLable -> getLabel

README.md
修改 sh 为 bash，避免有些操作系统默认 shell 不是 bash 时引起的错误。
=> docs: 修改 Readme 中快速安装命令

backend/src/main/java/io/metersphere/api/dto/definition/request/sampler/MsHTTPSamplerProxy.java, frontend/src/business/components/api/definition/components/ApiVariableAdvance.vue, frontend/src/business/components/api/test/components/ApiVariableAdvance.vue, frontend/src/business/components/api/test/components/environment/ApiScenarioVariables.vue, frontend/src/business/components/api/test/components/environment/ApiVariableAdvance.vue, frontend/src/business/components/api/test/components/environment/ApiVariableSetting.vue
--bug=1016095 --user=王孝刚 【系统设置】工作空间 - 环境管理 - 创建环境页面，通用配置处，点击"高级设置"的相关问题
https://www.tapd.cn/55049933/s/1230602
=> refactor(系统设置): 优化环境配置相关设置

README.md
=> chore：去掉下载数 badge

README.md
=> chore：更新 README 中的 UI 展示图

README.md
=> chore(docs)：优化 README
